import { Main } from 'next/document'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
    return (
        <div className={styles.container}>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon3.ico" />
            </Head>

            <main className={styles.main}>
                <h1 className={styles.title}>
                    Pure Water Life
                </h1>

                <p className={styles.description}>
                    Tellus rutrum tellus pellentesque eu
                </p>

                <div className={styles.grid}>
                    <a href="" className={styles.card}>
                        <h2>Card 1 &rarr;</h2>
                        <p>Lorem ipsum dolor sit amet consectetur</p>
                    </a>

                    <a href="" className={styles.card}>
                        <h2>Card 2 &rarr;</h2>
                        <p>Learn about Next.js in an interactive</p>
                    </a>

                    <a href="" className={styles.card}>
                        <h2>Card 3 &rarr;</h2>
                        <p>Duis aute irure dolor in reprehenderit</p>
                    </a>

                    <a href="" className={styles.card}>
                        <h2>Card 4 &rarr;</h2>
                        <p>Excepteur sint occaecat cupidatat non proident</p>
                    </a>
                </div>
            </main>

            <footer className={styles.footer}>
                <p>555-555-5555 | email@gmail.com</p>
            </footer>
        </div>
    )
}